Create Models
rafarosa92/heath_history pull request #2
Opened 2020-12-10 01:08 UTC by FabioCoelho27

[Issue](https://trello.com/c/ec2otYiz/14-criar-models-pessoa)

2020-12-10 23:41 UTC, rafarosa92 commented on db/migrate/20201210001742_create_exams.rb
> +      t.string :description
description tem que ser text

2020-12-10 23:43 UTC, rafarosa92 commented on app/models/exam.rb
> +  belongs_to :appointment
Falta um has_many_attach :documents nesse model pra poder colocar os arquivos dos exames

2020-12-10 23:46 UTC, rafarosa92 commented on app/models/shared_history.rb
> +  belongs_to :appointment
adicionar a referencia do shared_user_id e owner_user_id

2020-12-10 23:48 UTC, rafarosa92 commented on app/models/treatment.rb
> +end
colocar referencia do appointment_id user_id e colocar has_one_attach :document

2020-12-10 23:48 UTC, rafarosa92 commented on db/migrate/20201210000916_create_treatments.rb
> +      t.string :kind
kind tem que ser um int pra receber um enum

2020-12-10 23:49 UTC, rafarosa92 commented on db/migrate/20201210000916_create_treatments.rb
> +      t.string :kind_treatment
remover kind_treatment coluna duplicada

2020-12-10 23:50 UTC, rafarosa92 commented on db/migrate/20201210001357_create_appointments.rb
> +      t.references :treatment, null: false, foreign_key: true
remover referencia treatment_id

2020-12-11 17:31 UTC, rafarosa92 commented on app/models/exam.rb
> +  belongs_to :appointment
errei a sintaxe era pra ser has_many_attached

2020-12-11 17:34 UTC, rafarosa92 requested changes

2020-12-11 17:34 UTC, rafarosa92 commented on app/models/treatment.rb
> +end
errei a sintaxe era pra ser has_one_attached

2020-12-11 17:34 UTC, rafarosa92 commented on app/models/exam.rb
> +  belongs_to :appointment
errei a sintaxe era pra ser has_many_attached

2020-12-11 23:59 UTC, valterfernandesdev approved these changes

2020-12-12 00:00 UTC, rafarosa92 approved these changes

2020-12-12 00:00 UTC, merged